config/routes.rb
Rails.application.routes.draw do
  root 'recipes#top'
  devise_for :users
  resources :recipes do
    collection do
      get 'search'
    end
    resources :comments, only:[:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :session
    user ||= User.new
    if user.guest?
      can :read, :all
    else
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many_attached :images
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum role: { general: 1, guest: 2 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe
  has_one_attached :avatar

  def self.guest
    find_or_create_by!(email: 'guest@example.com', role: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  authorize_resource class: false

  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to recipes_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.find(params[:id])
    if current_user.id == @comment.user.id
      @comment.destroy
      redirect_to recipe_path(params[:recipe_id])
    else
      redirect_to recipe_path(params[:recipe_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content,:recipe_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(recipe_id: params[:recipe_id])
    favorite.save
    redirect_to request.referer, notice: 'お気に入り登録しました！'
  end

  def destroy
    favorite = Favorite.find_by(recipe_id: params[:recipe_id], user_id: current_user.id)
    favorite.destroy
    redirect_to request.referer, notice: 'お気に入り解除しました！'
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:top]
  before_action :set_q, only: [:index, :search]
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.with_attached_images.includes(:user).order(:updated_at,:created_at).reverse_order
    @my_recipes = current_user.recipes.order(:updated_at,:created_at).reverse_order
    @all_ranks = Recipe.find(Favorite.group(:recipe_id).order('count(recipe_id) desc').limit(5).pluck(:recipe_id))
    gon.instagram_access_token = ENV['INSTAGRAM_ACCESS_TOKEN']
    gon.instagram_id = ENV['INSTAGRAM_ID']
  end

  def search
    @results = @q.result
    @my_results = @my_q.result
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def show
    @recipe = Recipe.with_attached_images.find(params[:id])
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user)
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipes_path
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private
  def top
  end

  def recipe_params
    params.require(:recipe).permit(:title,:process1,:process2,:process3, images: [])
  end

  def set_q
    @q = Recipe.with_attached_images.includes(:user).ransack(params[:q])
    @my_q = current_user.recipes.ransack(params[:q])
  end

  def ensure_user
    @recipes = current_user.recipes
    @recipe = @recipes.find_by(id: params[:id])
    redirect_to recipes_path unless @recipe
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.with_attached_avatar.find(params[:id])
    @favorite_recipes = @user.favorite_recipes.with_attached_images.includes(:user, :images_attachments).order(:updated_at, :created_at).reverse_order
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to user_path(current_user.id)
    end
  end

  private

  def user_params
    params.fetch(:user, {}).permit(:avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>3 step recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= include_gon %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <div class="hwrapper">
      <div class="header">
        <h1><%= link_to "3 step recipes", recipes_path, class:"userList text-white" %></h1>
        <div class="hamburger_menu">
          <%= render "shared/login" %>
        </div>
      </div>
    </div>
    <%= yield %>
    <a href="#" class="back-to-top">▲</a>
    <%= javascript_pack_tag 'recipe/index' %>
    <footer></footer>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="main_page">
  <div class="main_in_page">
  <%= notice %>
    <div class="search_form">
      <%= search_form_for @q, url: search_recipes_path do |f| %>
        <%= f.label :title_cont, 'キーワード検索' %>
        <div class="search_block">
          <%= f.search_field :title_cont, placeholder: "Recipe Keywords" %>
          <%= f.button :type => "submit", style: 'border-style: none;' do %>
            <i class="fa fa-search"></i>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <h3>All user's recipes</h3>
    <div class="carousel">
    <ul class="carousel-area">
      <% @recipes.each do |recipe| %>
        <%= link_to(recipe_path(recipe), class:"userList text-dark", id: "all_recipes") do %>
          <li class="carousel-list">
            <div class="card card-skin">
              <div class="card__imgframe">
                <% if recipe.images.blank? %>
                  <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
                <% else %>
                  <%= image_tag rails_blob_path(recipe.images[2]), size: '303x178' %>
                <% end %>
              </div>
              <div class="card__textbox">
                <div class="card__titletext">
                  <% if recipe.title.blank? %>
                    タイトルなし
                  <% else %>
                    <%= recipe.title %>
                  <% end %>
                </div>
                <div class="card__overviewtext">
                  <div class="recipe_username">Username:<%= recipe.user.username %></div>
                  <div class="recipe_edit_delete_link">
                    <% if user_signed_in? && current_user.id == recipe.user_id %>
                      <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                      <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                    <% end %>
                  </div>
                </div>
                <% if user_signed_in? %>
                  <% if recipe.favorited_by?(current_user) %>
                    <p>
                      <span>お気に入り解除: </span>
                      <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                        <i class="fa fa-heart unlike-btn"></i>
                      <% end %>
                      <span>お気に入り数: </span>
                      <%= recipe.favorites.count %>
                    </p>
                  <% else %>
                    <p>
                      <span>お気に入り登録: </span>
                      <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                        <i class="fa fa-heart like-btn"></i>
                      <% end %>
                      <span>お気に入り数: </span>
                      <%= recipe.favorites.count %>
                    </p>
                  <% end %>
                <% else %>
                  <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    </div>
    <br>
    <br>
    <div class="arow-wrap">
      <div class="arrow-left">
        <button class="arrow-btn js-btn-back" type="button"></button>
      </div>
      <div class="arrow-right">
        <button class="arrow-btn js-btn-next" type="button"></button>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="container main_page_my_recipe_container">
      <div class="row my_recipe_row">
        <div class="my_recipe_title col-sm-12">
          <h3>My recipe</h3>
        </div>
      <% @my_recipes.each do |recipe| %>
        <%= link_to(recipe_path(recipe), class:"userList text-dark", id:"my_recipes") do %>
          <div class="card_contents1 col-xs-12 col-md-4">
            <div class="card1 my-recipe-card-skin">
              <div class="card__imgframe">
                <% if recipe.images.blank? %>
                  <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
                <% else %>
                  <%= image_tag recipe.images[2], size: '303x178' %>
                <% end %>
              </div>
              <div class="card__textbox">
                <div class="card__titletext">
                  <% if recipe.title.blank? %>
                    タイトルなし
                  <% else %>
                    <%= recipe.title %>
                  <% end %>
                </div>
                <div class="card__overviewtext">
                  <div class="recipe_username">Username:<%= recipe.user.username %></div>
                  <div class="recipe_edit_delete_link">
                    <% if user_signed_in? && current_user.id == recipe.user_id %>
                      <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                      <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                    <% end %>
                  </div>
                </div>
                <% if user_signed_in? %>
                  <% if recipe.favorited_by?(current_user) %>
                    <p>
                      <span>お気に入り解除: </span>
                      <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                        <i class="fa fa-heart unlike-btn"></i>
                      <% end %>
                      <span>お気に入り数: </span>
                      <%= recipe.favorites.count %>
                    </p>
                  <% else %>
                    <p>
                      <span>お気に入り登録: </span>
                      <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                        <i class="fa fa-heart like-btn"></i>
                      <% end %>
                      <span>お気に入り数: </span>
                      <%= recipe.favorites.count %>
                    </p>
                  <% end %>
                <% else %>
                  <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="container main_page_my_recipe_container">
      <div class="row my_recipe_row">
        <div class="my_recipe_title col-sm-12">
          <h3>Favorite recipe's ranking</h3>
        </div>
        <% @all_ranks.each do |recipe| %>
          <%= link_to(recipe_path(recipe), class:"userList text-dark") do %>
            <div class="card_contents col-xs-12 col-md-4">
              <div class="card1 my-recipe-card-skin">
                <div class="card__imgframe">
                  <% if recipe.images.blank? %>
                    <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
                  <% else %>
                    <%= image_tag recipe.images[2], size: '303x178' %>
                  <% end %>
                </div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    <% if recipe.title.blank? %>
                      タイトルなし
                    <% else %>
                      <%= recipe.title %>
                    <% end %>
                  </div>
                  <div class="card__overviewtext">
                    <div class="recipe_username">Username:<%= recipe.user.username %></div>
                    <div class="recipe_edit_delete_link">
                      <% if user_signed_in? && current_user.id == recipe.user_id %>
                        <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                        <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                      <% end %>
                    </div>
                  </div>
                  <% if user_signed_in? %>
                    <% if recipe.favorited_by?(current_user) %>
                      <p>
                        <span>お気に入り解除: </span>
                        <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                          <i class="fa fa-heart unlike-btn"></i>
                        <% end %>
                        <span>お気に入り数: </span>
                        <%= recipe.favorites.count %>
                      </p>
                    <% else %>
                      <p>
                        <span>お気に入り登録: </span>
                        <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                          <i class="fa fa-heart like-btn"></i>
                        <% end %>
                        <span>お気に入り数: </span>
                        <%= recipe.favorites.count %>
                      </p>
                    <% end %>
                  <% else %>
                    <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <br>
    <br>
    <h3 class="instagram">Instagram</h3>
    <h3 id="insta"></h3>
    <br>
    <br>
    <div class="container new_recipe">
      <div class="row">
        <div class="new_recipe_button col-12">
          <%= button_to "Create a new recipe", {controller: "recipes", action: "new"}, {method: :get, class: "new_path_button" } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/search.html.erb
<div class="main_page">
  <div class="main_in_page">
    <%= notice %>
    <h3>ALL recipes</h3>
    <div class="container main_page_my_recipe_container">
      <div class="row my_recipe_row">
        <% @results.each do |recipe| %>
          <%= link_to(recipe_path(recipe), class:"userList text-dark", id: "all_recipes") do %>
            <div class="card_contents col-xs-12 col-md-4">
              <div class="card card-skin">
                <div class="card__imgframe">
                  <% if recipe.images.blank? %>
                    <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
                  <% else %>
                    <%= image_tag recipe.images[2], size: '303x178' %>
                  <% end %>
                </div>
                <div class="card__textbox">
                  <div class="card__titletext">
                    <% if recipe.title.blank? %>
                      タイトルなし
                    <% else %>
                      <%= recipe.title %>
                    <% end %>
                  </div>
                  <div class="card__overviewtext">
                    <div class="recipe_username">Username:<%= recipe.user.username %></div>
                    <div class="recipe_edit_delete_link">
                      <% if user_signed_in? && current_user.id == recipe.user_id %>
                        <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                        <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                      <% end %>
                    </div>
                  </div>
                  <% if user_signed_in? %>
                    <% if recipe.favorited_by?(current_user) %>
                      <p>
                        <span>お気に入り解除: </span>
                        <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                          <i class="fa fa-heart unlike-btn"></i>
                        <% end %>
                        <span>お気に入り数: </span>
                        <%= recipe.favorites.count %>
                      </p>
                    <% else %>
                      <p>
                        <span>お気に入り登録: </span>
                        <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                          <i class="fa fa-heart like-btn"></i>
                        <% end %>
                        <span>お気に入り数: </span>
                        <%= recipe.favorites.count %>
                      </p>
                    <% end %>
                  <% else %>
                    <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <br>
    <h3>My recipe</h3>
    <div class="favorite_block">
      <% @my_results.each do |recipe| %>
        <%= link_to(recipe_path(recipe), class:"userList text-dark", id:"my_recipes") do %>
          <div class="card card-skin">
            <div class="card__imgframe">
              <% if recipe.images.blank? %>
                <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
              <% else %>
                <%= image_tag recipe.images[2], size: '303x178' %>
              <% end %>
            </div>
            <div class="card__textbox">
              <div class="card__titletext">
                <% if recipe.title.blank? %>
                  タイトルなし
                <% else %>
                  <%= recipe.title %>
                <% end %>
              </div>
              <div class="card__overviewtext">
                <div class="recipe_username">Username:<%= recipe.user.username %></div>
                <div class="recipe_edit_delete_link">
                  <% if user_signed_in? && current_user.id == recipe.user_id %>
                    <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                    <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                  <% end %>
                </div>
              </div>
              <% if user_signed_in? %>
                <% if recipe.favorited_by?(current_user) %>
                  <p>
                    <span>お気に入り解除: </span>
                    <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                      <i class="fa fa-heart unlike-btn"></i>
                    <% end %>
                    <span>お気に入り数: </span>
                    <%= recipe.favorites.count %>
                  </p>
                <% else %>
                  <p>
                    <span>お気に入り登録: </span>
                    <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                      <i class="fa fa-heart like-btn"></i>
                    <% end %>
                    <span>お気に入り数: </span>
                    <%= recipe.favorites.count %>
                  </p>
                <% end %>
              <% else %>
                <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <div class="search_top_link col-12">
      <%= link_to "トップページへ戻る", recipes_path %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="main_page">
  <div class="recipe_title">Recipe Title:<%= @recipe.title %></div>
  <div class="recipe_title">Recipe creator's username:<%= @recipe.user.username %></div>
  <div class="recipe_detail_contents container">
    <div class="row">
      <div class="main_left col-sm-12 col-md-6">
        <div class="image_contents">
          <% if @recipe.images.attached? %>
            <% @recipe.images.each do |image| %>
            <div class="image_content_block">
              <%= image_tag image.variant(resize: "440x220!"), class: "img" %>
            </div>
            <% end %>
          <% else %>
            <div class="image_content_block">
              <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '440x220' %>
            </div>
            <div class="image_content">
              <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '440x220' %>
            </div>
            <div class="image_content">
              <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '440x220' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="main_right col-sm-12 col-md-6">
        <div class="process_block">
          <p>Recipe procedure①</p>
          <%= @recipe.process1 %>
        </div>
        <div class="process_block">
          <p>Recipe procedure②</p>
          <%= @recipe.process2 %>
        </div>
        <div class="process_block">
          <p>Recipe procedure③</p>
          <%= @recipe.process3 %>
        </div>
      </div>
    </div>
  </div>
  <div class="comment_block">
  <h2>コメント一覧</h2>
    <div class="comment_main">
      <% @comments.each do |c| %>
        <div class="comment_text">
          <%= c.user.username %>
          <br>
          <div><%= c.comment_content %></div>
          <br>
          <%= link_to "Delete a comment", recipe_comment_path(c.recipe.id,c.id), data: {confirm: '本当に削除しますか？'}, method: :delete %>
        </div>
      <% end %>
    </div>
    <div class="comment_button">
      <p>コメント記入</p>
      <%= form_with model: [@recipe, @comment] do |f| %>
        <%= f.text_field :comment_content %>
        <%= f.hidden_field :recipe_id, value: @recipe.id %>
        <br>
        <br>
        <%= f.submit 'コメントする' %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_login.html.erb
<span class="nav_toggle">
  <i></i>
  <i></i>
  <i></i>
</span>
<nav class="nav">
  <ul class="nav_menu_ul">
    <li class="nav_menu_li"><%= link_to 'サインアップ', new_user_registration_path, class:"userList text-dark" %></li>
    <li class="nav_menu_li"><%= link_to 'ログイン', new_user_session_path, class:"userList text-dark" %></li>
    <li class="nav_menu_li"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"userList text-dark" %></li>
    <li class="nav_menu_li"><%= link_to 'メインページ', recipes_path, class:"userList text-dark" %></li>
    <li class="nav_menu_li"><%= link_to 'レシピ投稿ページ', new_recipe_path, class:"userList text-dark" %></li>
    <li class="nav_menu_li">
      <% if user_signed_in? %>
        <%= link_to 'マイページ', user_path(current_user.id), class:"userList text-dark" %>
      <% end %>
    </li>
    <li class="nav_menu_li">
      <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:"userList text-dark" %>
    </li>
    <li class="nav_menu_li">
      <%= link_to 'Instagram', "https://www.instagram.com/", method: :post, class:"userList text-dark" %>
    </li>
  </ul>
</nav>
<script type="text/javascript">
$('.nav_toggle').on('click', function () {
  $('.nav_toggle, .nav').toggleClass('show');
});
</script>

app/views/users/show.html.erb
<div class="main_page">
  <h3>My plofile</h3>
  <div class="row my_page_main">
    <div class="my_image col-xs-12 col-md-6">
      <div>
      <% if current_user.avatar.blank? %>
        <%= image_tag 'noimage.jpg', class: 'sized' %>
      <% else %>
        <%= image_tag current_user.avatar,class: 'sized' %>
      <% end %>
      </div>
      <br>
      <div>
      <%= form_with model: @user do |form| %>
        <%= form.label :avatar, 'プロフ画像編集' %>
        <%= form.file_field :avatar  %>
        <div>
          <%= form.submit "Update my profile image", class: 'update_image_button' %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="name_follow col-xs-12 col-md-6">
      <p>ユーザー名：<%= current_user.username %></p>
      <p>アドレス：<%= current_user.email %></p>
      <p>レシピ投稿数：<%= current_user.recipes.count %></p>
      <p>お気に入りしたレシピの数：<%= @favorite_recipes.count %></p>
    </div>
  </div>
  <h3>My favorite recipes</h3>
  <div class="my_recipe_container">
    <% @favorite_recipes.each do |recipe| %>
      <%= link_to(recipe_path(recipe), class:"userList text-dark") do %>
        <div class="card card-skin">
          <div class="card__imgframe">
            <% if recipe.images.blank? %>
              <%= image_tag "/images/black-bean-close-up-cooked-16407741.png", size: '303x178' %>
            <% else %>
              <%= image_tag recipe.images[2], size: '303x178' %>
            <% end %>
          </div>
          <div class="card__textbox">
            <div class="card__titletext">
              <% if recipe.title.blank? %>
                タイトルなし
              <% else %>
                <%= recipe.title %>
              <% end %>
            </div>
            <div class="card__overviewtext">
              <div class="recipe_username">Username:<%= recipe.user.username %></div>
              <div class="recipe_edit_delete_link">
                <% if user_signed_in? && current_user.id == recipe.user_id %>
                  <%= link_to 'Edit', edit_recipe_path(recipe), class:"userList text-dark recipe_edit" %>
                  <%= link_to 'Delete', recipe_path(recipe), method: :delete, class:"userList text-dark recipe_delete" %>
                <% end %>
              </div>
            </div>
            <% if user_signed_in? %>
              <% if recipe.favorited_by?(current_user) %>
                <p>
                  <span>お気に入り解除: </span>
                  <%=link_to recipe_favorites_path(recipe.id), method: :delete do %>
                    <i class="fa fa-heart unlike-btn"></i>
                  <% end %>
                  <span>お気に入り数: </span>
                  <%= recipe.favorites.count %>
                </p>
              <% else %>
                <p>
                  <span>お気に入り登録: </span>
                  <%=link_to recipe_favorites_path(recipe.id), method: :post do %>
                    <i class="fa fa-heart like-btn"></i>
                  <% end %>
                  <span>お気に入り数: </span>
                  <%= recipe.favorites.count %>
                </p>
              <% end %>
            <% else %>
              <p><span>お気に入り数: </span><%= recipe.favorites.count %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="top_back_button">
    <%= link_to  recipes_path, class: 'btn btn-default' do %>
      <i class="fa fa-arrow-left"></i>
      <span>トップページへ戻る</span>
    <% end %>
  </div>
</div>